// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qhiuxlsjweadsixcaxba.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFoaXV4bHNqd2VhZHNpeGNheGJhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI1MzI1NDUsImV4cCI6MjA1ODEwODU0NX0.TlGpnOI5fj0821rzF9THMy8jPGWOszT-EIR2b_dW5s0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);